apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-account
  labels:
    app: create-account-app
  namespace: accoun-update
spec:
  selector:
    matchLabels:
      app: create-account-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: create-account-app
    spec:
      containers:
      - name: create-account-app
        image: conano/create-account-handler:0.0.1-2
        envFrom:
        - secretRef:
            name: create-account-secret
        imagePullPolicy: IfNotPresent        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        